#ifndef SIMULATORPARAMETER_H_INCLUDED
#define SIMULATORPARAMETER_H_INCLUDED


//#define LEVEL_FP_
#define VECTOR_FP_
//#define FULL_SCAN_


#define FP_LEVEL 12
#define VFP_LENGTH 20

#define fs_OSG_Percent 1.0


#endif // SIMULATORPARAMETER_H_INCLUDED
